# Generated by Django 4.0.1 on 2022-01-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='group_category',
            field=models.CharField(default='anonymous', max_length=100),
            preserve_default=False,
        ),
    ]
