# Generated by Django 4.0.1 on 2022-02-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_groups_group_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'ordering': ['group_category']},
        ),
        migrations.AlterField(
            model_name='groups',
            name='group_name',
            field=models.CharField(max_length=200),
        ),
    ]
